### ISSUE TITLE
Taterzens Broken?

### ISSUE THREAD

**Issue by DillonB07** [samolego/Taterzens#6] opened 2021-04-14 11:25 UTC
LuckPerms doesn't detect Taterzens permissions and it is impossible to use Gradle with Taterzens.
I did 
```
git clone https://github.com/samolego/Taterzens
cd Taterzens
./gradlew
```
That is the output from `./gradlew`
[https://pastebin.com/4mbnYv4E](https://pastebin.com/4mbnYv4E)
The LuckPerms thing might just be my server. If you want to have a look yourself, the IP is `145.239.252.39:25591`
I gave you op level 4 just in case you do decide to join(To view the mods on the server do `/mod list`.

**Comment by samolego** [comment] 2021-04-14 12:03
Nucleoid's maven is down, meaning that disguiselib cannot be fetched. Gegy said it will be fixed by April 20th. Meanwhile you can use jitpack.

Regarding permissions, I can take a look. Thanks for report

**Comment by DillonB07** [comment] 2021-04-14 12:36
In case it is needed, I am using the latest build of LuckPerms.
That is the one with the Carpet /player support.

**Comment by samolego** [comment] 2021-04-17 14:08
Humm, I cannot reproduce this on my local server. Permissions seem to work fine, I can change them to true/false and they update accordingly ... 🤔

**Comment by DillonB07** [comment] 2021-04-17 14:45
Permissions aren't working with CommandSpy either. Everyone with level 1 op can see the messages without the permissions in LuckPerms.
Maybe a mod is stopping it working?

**Closed** 2021-04-20 20:34 UTC
