### ISSUE TITLE
Not compatible with Galosphere Shares the same ID[Forge / Fabric]

### ISSUE THREAD

**Issue by Zytinx** [samolego/Taterzens#123] opened 2022-12-03 10:00 UTC
**Describe the bug**
Using Galosphere mod and it doesnt allow me to create any npc because of a duplicated id 17. I tried it without the mod and it works but then the server crashes when someone goes into that biome. 

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.19.2
* Taterzens 1.11.1

**Comment by HOLYSPAGETI** [comment] 2022-12-03 18:46
Hello! I'm experiencing the same problem but I'm not using Galosphere, can you tell me how to find which id is being duplicated?

**Comment by samolego** [comment] 2022-12-03 18:55
Duplicate of #112

**Closed by samolego** 2022-12-03 18:55 UTC
