### ISSUE TITLE
Inventory getting deleted after the use of the UI provided by /npc

### ISSUE THREAD

**Issue by Bwapt** [samolego/Taterzens#163] opened 2023-08-04 21:24 UTC
**Describe the bug**
The user inventory is deleted after using a command on the user interface provided by /npc

**Platform(s)**
- [x] Fabric
- [ ] Forge

**Environment(s)**
- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.20.1
* Taterzens 1.11.6

**To Reproduce**
1. Launch a game
2. Put stuff in your inventory
3. Use /npc, and use a command (create in the current example)
4. Watch your inventory getting wiped

**Expected behavior**
The inventory doesn't not disappear

**Logs**
Don't know where to find logs sorry.

**Additional context**
The inventory is getting deleted right after the closing of the UI.

https://github.com/samolego/Taterzens/assets/114883283/e3e09263-abee-476c-a7b4-2ceae9b2d778

**Comment by Bwapt** [comment] 2023-08-04 21:28
Sorry I've seen that this has been already reported

**Comment by samolego** [comment] 2023-09-02 07:14
Closing as duplicate of #154

**Closed by samolego** 2023-09-02 07:14 UTC
