### ISSUE TITLE
Menu GUI not working[Forge]

### ISSUE THREAD

**Issue by RedRowBoat** [samolego/Taterzens#88] opened 2022-03-31 04:46 UTC
I am trying to use the menu's that the mod provides to alter things, like creating more than just one page of trades for trader NPC's (using the trader npc add-on) or to change the position of the npc, however the menu isn't working and I can only use commands.

Forge 1.18.1 Server

Taterzens version 1.8.4 forge

**Comment by samolego** [comment] 2022-03-31 05:55
Duplicate of #73 .

**Closed by samolego** 2022-03-31 05:55 UTC
