### ISSUE TITLE
Incompatibility with Gunpowder-MC(or latest Fabric API)

### ISSUE THREAD

**Issue by DillonB07** [samolego/Taterzens#4] opened 2021-03-24 15:00 UTC
This mod is incompatible with Gunpowder-MC(with utilities extension) or the latest Fabric API at point of writing.
I used this mod perfectly before adding Gunpowder and the latest Fabric API.
This is the issue we were talking about on Discord, only now I found out the conflicting mods.
Would it be possible for you to add support or should I just remove gunpowder?(Your mod is better so I would remove Gunpowder if I had to remove one)

**Comment by samolego** [comment] 2021-03-24 18:13
No, I'd love to make it not conflict with Gunpowder ...
The problem is that I'm kinda stuck with releases if Taterzens were really the one to cause the corruptions ...

**Comment by DillonB07** [comment] 2021-03-25 10:14
Yes Gunpowder+Taterzens is the "corruption combo".
Or Taterzens and the latest Fabric API
I'd been using Taterzens(0.2.0) before I added Gunpowder + Gunpowder Utilities perfectly fine. It was only after I added Gunpowder and updated the Fabric API that Taterzens stopped me joining. I can tell it was Taterzens because it was the /npc create command. The other commands were fine.

**Comment by DillonB07** [comment] 2021-03-25 10:15
I am unable to actually test it, due to the unfortunate issue of not being able to access Minecraft for a few months minimum.

**Comment by samolego** [comment] 2021-03-25 19:40
I've checked this more and reported issue in Gunpowder, https://github.com/Gunpowder-MC/GunpowderUtilities/issues/17
as the fault is missing [`null` check](https://github.com/Gunpowder-MC/GunpowderUtilities/blob/af8551ccc352513ae10b16dd506abe62837fe50a/src/main/java/io/github/gunpowder/mixin/utilities/PlayerListS2CPacketMixin_Utilities.java#L53).

**Comment by DillonB07** [comment] 2021-03-26 19:28
So I just have to wait until Gunpowder fix this.
If they even will as the last thing on their repo was on the 17th January

**Comment by samolego** [comment] 2021-04-07 05:24
This has been fixed in gunpowder :)

**Closed by samolego** 2021-04-07 05:24 UTC
